// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PostalTracker.Orchestrator.Host.DAL;

#nullable disable

namespace PostalTracker.Orchestrator.Host.Migrations
{
    [DbContext(typeof(PostalStateContext))]
    partial class PostalStateContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PostalTracker.Orchestrator.Host.Components.PostalState", b =>
                {
                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<string>("AddressDelivery")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("AddressSender")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("CurrentState")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<Guid?>("InWayDurationToken")
                        .HasColumnType("uuid");

                    b.Property<string>("Timestamp")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.HasKey("CorrelationId")
                        .HasName("PK_UserProfile");

                    b.ToTable("PostalStates", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
